### ISSUE TITLE
Goals for this repo

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/Hackathons#2]
This should have a Hackathon starter kit of sorts:
- [ ] Tips on how to organize a hackathon
- [ ] Sample schedules
- [ ] Ideas for people to work on curated by the team members
- [ ] How to get sponsors and generate interest
- [ ] Other things?

There should be a generator to create a sample site or info to paste to things like meetup
