### ISSUE TITLE
section for running meetups

### ISSUE THREAD

**Issue by ahmadnassri** [yeoman/Hackathons#3]
This should have a meetup guideline:
- [ ] Tips on how to organize a meetup
- [ ] directory of global meetups
- [ ] How to get sponsors and generate interest
- [ ] Other things?
